# Generated by Django 5.2 on 2025-04-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=255)),
                ('expires_in', models.BigIntegerField()),
                ('expires_at', models.BigIntegerField()),
                ('last_synced', models.BigIntegerField()),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('token_type', models.CharField(max_length=255)),
                ('scope', models.CharField(max_length=255)),
            ],
        ),
    ]
